Repository dmacvicar/terraform-provider-libvirt, pull requests merged in 2019-09, with the labels that each got.

#627 feat(domain): add fw_cfg_name option
  examples/v0.12/flatcar-linux/README.md
  examples/v0.12/flatcar-linux/ignition.tf
  examples/v0.12/flatcar-linux/main.tf
  examples/v0.12/flatcar-linux/units/00-wired.network
  examples/v0.12/flatcar-linux/units/20-etcd-member.conf
  libvirt/domain.go
  libvirt/resource_libvirt_domain.go
  libvirt/resource_libvirt_domain_test.go
  website/docs/r/domain.html.markdown
Labels: status/approved

#631 Added a contrib folder which contains Docker examples
  README.md
  contrib/Alpine/Dockerfile_all_in_one
  contrib/Alpine/Dockerfile_build_dependent
  contrib/Alpine/README.md
  contrib/Build/Dockerfile_glibc
  contrib/Build/Dockerfile_musl
  contrib/Build/README.md
  contrib/Debian/Dockerfile_all_in_one
  contrib/Debian/Dockerfile_build_dependent
  contrib/Debian/README.md
  contrib/README.md
  contrib/openSUSE/Dockerfile_all_in_one
  contrib/openSUSE/Dockerfile_build_dependent
  contrib/openSUSE/README.md
Labels: status/approved

#643 Update network.markdown
  website/docs/r/network.markdown
Labels: needinfo

#646 Don't error when a volume exist already during apply
  libvirt/resource_libvirt_volume.go
Labels: RFC
